### ISSUE TITLE
Change API

### ISSUE THREAD

**Issue by dimasmaulana99** [north-road/qgis-google-maps-geocoder#2]
How to change the API if I already applied an API?

**Comment by dbartecchi** [comment]
I have the exact same issue as @dimasmaulana99

**Comment by cefect** [comment]
bump

**Comment by cefect** [comment]
Looks like it's stored in QGIS.ini

[plugins]
google_maps\api_key=

To find this, go to Settings>User Profiles > Open Active Profile Folder
Then look in the QGIS directory

**Comment by nyalldawson** [comment]
Just go to the "google maps" page in the QGIS options dialog 👍
